type: object
properties:
  id:
    type: integer
    description: 工作流ID
    example: 1
  name:
    type: string
    description: 工作流名称
    example: poetry-up-to-date
  desc:
    type: string
    description: 工作流描述
    example: poetry 持续构建
  env:
    $ref: "#/components/schemas/Env"
  stages:
    type: array
    items:
      $ref: "#/components/schemas/Stage"
  supportRelease:
    type: boolean
    description: 是否支持发布
    example: false
