type: object
properties:
  id:
    type: integer
    description: 产品唯一ID
    example: 1
  name:
    type: string
    description: 产品名称
    example: poetry
  desc:
    type: string
    description: 产品描述
    example: poetry 产品线
  teams:
    type: array
    items:
      $ref: "#/components/schemas/TeamLite"
    example:
      - id: 1
        name: Poetry开发组
  releaser:
    type: array
    items:
      $ref: "#/components/schemas/UserLite"
    example:
      - id: 2
        name: Alex
      - id: 3
        name: Bob